# Generated by Django 4.1.7 on 2023-04-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImLearnEng", "0002_wordauthors_words_delete_review"),
    ]

    operations = [
        migrations.AlterModelOptions(name="wordauthors", options={},),
        migrations.AlterModelOptions(name="words", options={},),
    ]
