# Generated by Django 4.1.7 on 2023-04-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImLearnEng", "0003_alter_wordauthors_options_alter_words_options"),
    ]

    operations = [
        migrations.RenameField(model_name="words", old_name="wordid", new_name="id",),
        migrations.RemoveField(model_name="wordauthors", name="wordid",),
        migrations.AlterField(
            model_name="wordauthors",
            name="id",
            field=models.IntegerField(
                db_column="wordId", primary_key=True, serialize=False
            ),
        ),
    ]
