# Generated by Django 4.1.7 on 2023-04-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImLearnEng", "0005_alter_wordauthors_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordauthors", old_name="id", new_name="_id",
        ),
        migrations.RenameField(model_name="words", old_name="id", new_name="_id",),
    ]
